# Generated by Django 3.2.9 on 2021-11-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=1024)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
